=== Kain1989/Kain_Sample/IOC_Container/src/test/resources/appContext/IOC_Container.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="beans">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="import"/>
        <xs:element maxOccurs="unbounded" ref="bean"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="import">
    <xs:complexType>
      <xs:attribute name="resource" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="bean">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="property"/>
      </xs:sequence>
      <xs:attribute name="class" use="required"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="lazy" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="property">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="list"/>
        <xs:element ref="ref"/>
        <xs:element ref="value"/>
        <xs:element ref="map"/>
      </xs:choice>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="map">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="entry"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="entry">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="list"/>
      </xs:sequence>
      <xs:attribute name="key" use="required" type="xs:NCName"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="value" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="list">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="value"/>
        <xs:element ref="ref"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ref">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="excludeRegions" type="xs:NCName"/>
          <xs:attribute name="includeRegions" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="value" type="xs:NCName"/>
</xs:schema>

=== Kain1989/Kain_Sample/IOC_Container/src/test/resources/appContext/appContext.xml
<?xml version="1.0" encoding="UTF-8"?>

<beans xmlns="../IOC_Container.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../IOC_Container.xsd">

    <import resource="appContext2.xml"/>

    <bean id="test" class="com.kain.ioc.container.test.TestInjection">
        <property name="name">
            <value>Test</value>
        </property>
    </bean>

    <bean id="entity" class="com.kain.ioc.container.test.model.Entity" lazy="false">
        <property name="list">
            <list>
                <value>list0</value>
                <value>list1</value>
                <ref includeRegions="CN">test</ref>
            </list>
        </property>
        <property name="map">
            <map>
                <entry key="key0" value="key0"/>
                <entry key="key1" ref="test"/>
                <entry key="key2">
                    <list>
                        <value>list0</value>
                        <value>list1</value>
                        <ref excludeRegions="CN">test</ref>
                    </list>
                </entry>
            </map>
        </property>
        <property name="name">
            <value>ICO_Container</value>
        </property>
        <property name="test">
            <ref>test</ref>
        </property>
    </bean>

</beans>
